# Generated by Django 5.2.10 on 2026-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Ameaça')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('level', models.CharField(choices=[('low', 'Baixo Risco'), ('medium', 'Médio Risco'), ('high', 'Alto Risco'), ('critical', 'CRÍTICO')], default='low', max_length=10, verbose_name='Nível de Risco')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido?')),
            ],
            options={
                'verbose_name': 'Ameaça',
                'verbose_name_plural': 'Ameaças',
                'ordering': ['-detected_at'],
            },
        ),
    ]
