# Generated by Django 5.2.10 on 2026-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('link', models.URLField(max_length=1000, unique=True, verbose_name='Link da Notícia')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('source', models.CharField(max_length=200, verbose_name='Fonte')),
                ('category', models.CharField(choices=[('vulnerability', 'Vulnerabilidade'), ('breach', 'Vazamento de Dados'), ('malware', 'Malware'), ('patch', 'Patch/Atualização'), ('general', 'Geral')], default='general', max_length=20, verbose_name='Categoria')),
                ('published_date', models.DateTimeField(verbose_name='Data de Publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-published_date'],
            },
        ),
        migrations.DeleteModel(
            name='Threat',
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['-published_date'], name='news_newsar_publish_efb9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category'], name='news_newsar_categor_ed8dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source'], name='news_newsar_source_2a5eed_idx'),
        ),
    ]
